[package]
name = "pathfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
near-min-api = { git = "https://github.com/INTEARnear/wallet" }
rhea-dcl-math = { path = "../rhea-dcl-math" }
pool-indexer = { path = "../pool-indexer" }
anyhow = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7.1"
lazy_static = "1"
tracing = "0.1.41"
borsh = "1.6.0"
bigdecimal = "0.4.10"
rustc-hash = "2.1.3"
smallvec = "1.15.1"
ruint = "1.20.1"
